version: '2'

services:
    mysql_localhost:
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=abc
            - MYSQL_DATABASE=wordpressdatbase
            - MYSQL_USER=root
            - MYSQL_PASSWORD=abc
            #- variables.env
        # hostname: localhost
        volumes:
           - ./dbdata:/var/lib/mysql/
        # volumes:
        #     - ./data/mysql:/docker-entrypoint-initdb.d    
        
    nginx_localhost:
        image: nginx
        restart: always
        ports:
            - "80:80"
        working_dir: /var/www
        volumes:
            - ./wordpress:/var/www/wordpress
            - ./conf/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - phpfpm
        links:
            - phpfpm

    phpfpm:
        image: phalconphp/php-apache:ubuntu-16.04
        restart: always
        ports:
            - "8080:80"
        working_dir: /var/www
        volumes:
            - ./wordpress:/var/www/wordpress
        depends_on:
            - mysql_localhost
        # hostname: webserver

   

